# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

env:
  parameter-store:
    CONSUMER_KEY_PLACEHOLDER: "CONSUMER_KEY"
    CONSUMER_SECRET_PLACEHOLDER: "CONSUMER_SECRET"
    ACCESS_TOKEN_PLACEHOLDER: "ACCESS_TOKEN"
    ACCESS_TOKEN_SECRET_PLACEHOLDER: "ACCESS_TOKEN_SECRET"
phases:
  install:
    runtime-versions:
      nodejs: 12  
    commands:
      - echo Installing Yarn...
      - npm install -g yarn
      - npm install -g mocha
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn
  build:
    commands:
      - echo Build started.
      - echo Running build.
      - yarn start
  post_build:
    commands:
      - echo Build completed.
# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages 
# used only for building and testing.
# ExpressJS apps will need other artifact directories included (bin/*, public/*, routes/*, views/* etc).
artifacts:
  files:
    - app.js
    - bin/*
    - index.html
    - package.json
    - node_modules/async/*
    - node_modules/lodash/*